# Generated by Django 3.2.16 on 2022-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="frequency",
            field=models.PositiveBigIntegerField(default=0, verbose_name="frequency"),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="license",
            field=models.JSONField(default=dict, verbose_name="license"),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="meanings",
            field=models.JSONField(default=dict, verbose_name="meanings"),
        ),
        migrations.AlterField(
            model_name="dictionary",
            name="phonetics",
            field=models.JSONField(default=dict, verbose_name="phonetics"),
        ),
    ]
