# Generated by Django 3.2.16 on 2022-11-23 20:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paras", "0002_auto_20221123_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictionary",
            name="source_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="source urls",
            ),
        ),
    ]
